[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/"
    [headers.values]
    Content-Type = "text/html"

[[headers]]
  for = "/*.html"
    [headers.values]
    Content-Type = "text/html"

[[headers]]
  for = "/*.js"
    [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
    [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/assets/*.js"
    [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/assets/*.css"
    [headers.values]
    Content-Type = "text/css"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200